In [1]:
import pandas as pd
from selenium import webdriver 
from selenium.webdriver.chrome.service import Service 
from selenium.webdriver.common.by import By 
import time

In [2]:
def inicializa_driver():
    # A classe Service é usada para iniciar uma instância do Chrome Webdriver
    service = Service()

    # webdriver.ChromeOptions é usada para definir a preferência para o browser do chrome
    options = webdriver.ChromeOptions()

    # Inicia-se a instância do Chrome Webdriver com as definidas "options" e "service"
    return webdriver.Chrome(service=service, options=options)

In [3]:
df = pd.read_excel("./Estudos Raciais.xlsx")  
df

               Nome                                           Trabalho
0      Aline Durans  https://repositorio.insper.edu.br/entities/pub...
1    Alisson Santos  https://repositorio.insper.edu.br/entities/pub...
2    Alisson Santos  https://repositorio.insper.edu.br/entities/pub...
3    Alisson Santos  https://repositorio.insper.edu.br/entities/pub...
4    Alisson Santos  https://repositorio.insper.edu.br/entities/pub...
..              ...                                                ...
603    Sérgio Firpo  https://repositorio.insper.edu.br/entities/pub...
604    Sérgio Firpo  https://repositorio.insper.edu.br/entities/pub...
605    Sérgio Firpo  https://repositorio.insper.edu.br/entities/pub...
606    Sérgio Firpo  https://repositorio.insper.edu.br/entities/pub...
607    Sérgio Firpo  https://repositorio.insper.edu.br/entities/pub...

[608 rows x 2 columns]

In [4]:
classificacao = []
data = [] 

driver = inicializa_driver()

for url in df["Trabalho"]:
    driver.get(url)
    time.sleep(0.75)


    try:
        tipo_doc = driver.find_element(
        "xpath",
        "//div[h2[text()='Tipo de documento']]//span").text

        classificacao.append(tipo_doc)
    except:
        classificacao.append("Não foi possível identificar o tipo do trabalho")



    try:    
        data_elem = driver.find_element(
        "xpath",
        "//div[h2[text()='Data']]//span").text
        
        data.append(data_elem)
    except:
        data.append("Não foi possível identificar a data do trabalho")

In [5]:
df.insert(loc=2, column="Data", value=data)
df.insert(loc=3, column="Categoria", value=classificacao)
df

,Nome,Trabalho,Data,Categoria
0,Aline Durans,https://repositorio.insper.edu.br/entities/pub...,2013,Trabalho de Evento
1,Alisson Santos,https://repositorio.insper.edu.br/entities/pub...,2024,Artigo de Periódico Noticioso
2,Alisson Santos,https://repositorio.insper.edu.br/entities/pub...,2022,Texto para discussão
3,Alisson Santos,https://repositorio.insper.edu.br/entities/pub...,2024,Relatório de pesquisa
4,Alisson Santos,https://repositorio.insper.edu.br/entities/pub...,2024,Relatório de pesquisa
...,...,...,...,...
603,Sérgio Firpo,https://repositorio.insper.edu.br/entities/pub...,2021,Trabalho de Conclusão de Curso
604,Sérgio Firpo,https://repositorio.insper.edu.br/entities/pub...,2018,Trabalho de Conclusão de Curso
605,Sérgio Firpo,https://repositorio.insper.edu.br/entities/pub...,2010,Texto para discussão
606,Sérgio Firpo,https://repositorio.insper.edu.br/entities/pub...,2015,Artigo Científico
607,Sérgio Firpo,https://repositorio.insper.edu.br/entities/pub...,2019,Trabalho de Conclusão de Curso

In [6]:
df.to_excel("Estudos Raciais Completo.xlsx", index=False)